version: '3.5'

services:
  postgres:
    container_name: postgres_api_estudo
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    # restart: unless-stopped

  pgadmin:
    container_name: pgadmin_api_estudo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@root.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '8081:80'
    depends_on:
      - postgres
    networks:
      - postgres

  redis:
    container_name: cache_api_estudo
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8082:8081'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis:
